export PATH=/usr/local/share/npm/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=~/bin:$PATH
export PATH=~/.rbenv/bin:$PATH

# Ensure rbenv exists before initializing it
command -v rbenv > /dev/null 2>&1
if [ $? -eq 0 ]; then
  eval "$(rbenv init -)"
fi

export PATH=./.bundle/bin:$PATH

export PS1='\[\e[1;39m\]\h:\[\e[1;34m\]\w\$\[\e[0m\] '

export LANG=en_GB.UTF-8

export EDITOR="vim"

# Required by bash-completion brew package
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# Grab the git-completion script with:
# curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash
if [ -f ~/.git-completion.bash ]; then
  source ~/.git-completion.bash
fi

if [ -f ~/.bash_local ]; then
   source ~/.bash_local
fi

if [ -f ~/.aliases ]; then
   source ~/.aliases
fi

# Magic Ruby settings to make tests run faster. Courtesy of Chris Zetter.
export RUBY_HEAP_MIN_SLOTS=1000000
export RUBY_HEAP_SLOTS_INCREMENT=1000000
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1
export RUBY_GC_MALLOC_LIMIT=1000000000
export RUBY_HEAP_FREE_MIN=500000
export RUBY_FREE_MIN=$RUBY_HEAP_FREE_MIN
export RUBY_GC_HEAP_FREE_SLOTS=$RUBY_FREE_MIN # For Ruby 2.1
export RUBY_GC_HEAP_INIT_SLOTS=$RUBY_HEAP_MIN_SLOTS # For Ruby 2.1

# Autocomplete for AWS CLI
complete -C aws_completer aws

# Autocomplete for homebrew
# Copied from https://docs.brew.sh/Shell-Completion
if type brew &>/dev/null; then
  for COMPLETION in $(brew --prefix)/etc/bash_completion.d/*
  do
    [[ -f $COMPLETION ]] && source "$COMPLETION"
  done
  if [[ -f $(brew --prefix)/etc/profile.d/bash_completion.sh ]];
  then
    source "$(brew --prefix)/etc/profile.d/bash_completion.sh"
  fi
fi

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# asdf - https://asdf-vm.com/
if [ -f $HOME/.asdf/asdf.sh ]; then
  . $HOME/.asdf/asdf.sh
fi
if [ -f $HOME/.asdf/completions/asdf.bash ]; then
  . $HOME/.asdf/completions/asdf.bash
fi

# chruby - https://github.com/postmodern/chruby
if [ -f /usr/local/share/chruby/chruby.sh ]; then
  source /usr/local/share/chruby/chruby.sh
fi

# Direnv
command -v direnv > /dev/null 2>&1
if [ $? -eq 0 ]; then
  eval "$(direnv hook bash)"
fi
