set nocompatible              " be iMproved, required
filetype off                  " required

let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rails'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'lambdatoast/elm.vim' " Elm syntax highlighting
Plug 'mileszs/ack.vim'     " Use `ack` from within vim
Plug 'Konfekt/FastFold'    " Attempt to make Vim more responsive when foldmethod=syntax
Plug 'https://github.com/thoughtbot/vim-rspec.git'

call plug#end()
filetype plugin indent on    " required

syntax on                    " Purdy syntax highlighting
set list                     " Show hidden characters (tabs, for example)
set listchars=tab:>-,trail:- " Highlight tabs with '>-' and trailing spaces with '-'
set number                   " Line number goodness
set ruler                    " Show row and column on the bottom right of the screen
set showmatch                " Show matching brackets
set expandtab                " Soft tabs (spaces instead of tabs)
set softtabstop=2            " Number of spaces in a soft tab
set tabstop=2                  " Indent 2 spaces
set shiftwidth=2               " Indent 2 spaces
set backspace=indent,eol,start " Make backspace work as I expect

set laststatus=2               " Always display status line

autocmd BufWritePre * %s/\s\+$//e  " Strip trailing whitespace on save

" Run rspec using \ r
nnoremap <silent> <leader>r :term bundle exec rspec %<cr>

set background=dark

" Use ag instead of ack
" From https://github.com/ggreer/the_silver_searcher#vim
let g:ackprg = 'ag --nogroup --nocolor --column'

" Custom command to run RSpec example on current line
command -range RSpecRunLine :term rspec %:<line1>
nnoremap <silent> <leader>rl :RSpecRunLine<cr>

" Custom command to run Rails test on current line
command -range RailsTestRunLine :term rails test %:<line1>
nnoremap <silent> <leader>rtl :RailsTestRunLine<cr>
